INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL) VALUES (1, 'jwooyong', '1', '정우용', 'j@gamil.com');
INSERT INTO USER (ID, USER_ID, PASSWORD, NAME, EMAIL) VALUES (2, 'test', '1', '테스터', 't@gamil.com');
INSERT INTO QUESTION ( ID, WRITER_ID, TITLE, CONTENTS, CREATE_DATE ) VALUES ( 1,1,'제목1','내용1', CURRENT_TIMESTAMP());
INSERT INTO QUESTION ( ID, WRITER_ID, TITLE, CONTENTS, CREATE_DATE ) VALUES ( 2,2,'제목2','내용2', CURRENT_TIMESTAMP());